# docker-compose.yml
version: "3.8"
services:
  weather-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./weather_data:/app/weather_data
      - ./weather_logs.db:/app/weather_logs.db
    restart: unless-stopped